### ISSUE TITLE
 Dbf5('file.dbf')  AssertionError  assert terminator == b'\r

### ISSUE THREAD

**Issue by AndreMikulec** [rnelsonchem/simpledbf#5]
Whenever I try to load a .dbf file I am getting an error.

``` python
>>> Dbf5('myfile.dbf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\TARGET\WinPython-64bit-3.3.5.9\python-3.3.5.amd64\lib\site-packages\simpledbf\simpledbf.py", line 557, in __init__
    assert terminator == b'\r'
AssertionError
>>>
```

I am using

``` text
simpledbf-0.2.6.tar.gz
```

on

``` text
Python 3.3.5 (v3.3.5:62cf4e77f785, Mar  9 2014, 10:35:05) [MSC v.1600 64 bit (AMD64)] on win32
```

Thanks,
Andre Mikulec

**Comment by jdovi** [comment]
I'm having the same problem.  Is there any plans on addressing this issue?

**Comment by daren-thomas** [comment]
I too have this problem with a file edited with the DBF Explorer.

**Comment by melanatech** [comment]
Any update on this?

**Comment by vanboom** [comment]
I have discovered that this is caused by unsupported column types:  Date/Time (Timestamp), and Memo by trial and error, i.e. removing columns and a little debuggin in simpledbf.py

**Comment by rnelsonchem** [comment]
My guess is that the assertion errors are a result of incorrect DBF file versions. There is a section in the README that explains which DBF versions are acceptable. 

Have a look at the table entitled "Database file header" on the [dbf Wikipedia page](https://en.wikipedia.org/wiki/.dbf). The very last byte of the header should be `0x0D`, which is is a [carriage return](http://www.bluesock.org/~willg/dev/ascii.html). If that is not true, then you might have a different file version. For example in [DBF version 7](http://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm), the header has a much different length, so this code will not process it correctly. 

You can check the DBF version info from the first byte of your file as follows: 
```
f = open('my.dbf', 'rb')
f.read(1)
```
[Convert](https://www.binaryhexconverter.com/hex-to-binary-converter) this hex value into binary. As per the [DBF7](http://www.dbase.com/Knowledgebase/INT/db7_file_fmt.htm) description, bits 0-2 tell you about the version number. For example, I downloaded the file "Health Indicator Attributes" from the [HRSA website](https://datawarehouse.hrsa.gov/data/datadownload/pcsa2010Download.aspx). When I checked the first byte, I got `'\x03'`, which converts to `0000 0011` in binary. The first three bits (on the far right, i.e. 011) are equivalent to 3, which according the DBF7 notes linked above indicates a DBF version 5 file.

I hope this helps. If you'd like, you can use this code as a template to create a DBF version 7 reader using the format link that I've provided. I only deal with older DBF versions, so I won't have any bandwidth to make updates to this project.

**Comment by erfannariman** [comment]
same issues, still no updates on this?

**Comment by architsingh15** [comment]
same issue, updates?

**Comment by rafdm** [comment]
is there any alternative for this library? As I can see there is no support

**Comment by Enriquesec** [comment]
same issues, still no updates on this?

**Comment by ritaalamino** [comment]
Same issue! 

```
File ~/.local/lib/python3.8/site-packages/simpledbf/simpledbf.py:557, in Dbf5.__init__(self, dbf, codec)
    554 self.columns = [f[0] for f in self.fields[1:]]
    556 terminator = self.f.read(1)
--> 557 assert terminator == b'\r'
    559 # Make a format string for extracting the data. In version 5 DBF, all
    560 # fields are some sort of structured string
```

**Comment by roks531** [comment]
Same problem here... Please any fix for this?

**Comment by eolchina** [comment]
Same problem here... any fix for this?
